-- MySQL Workbench Synchronization
-- Generated: 2021-03-17 11:22
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: tdlem

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `access_token` 
CHANGE COLUMN `valid` `is_valid` BIT(1) NOT NULL DEFAULT b'1' ;

ALTER TABLE `robot` 
CHANGE COLUMN `active` `is_active` BIT(1) NOT NULL DEFAULT b'1' ,
CHANGE COLUMN `creation_date` `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `robot_assignment` 
CHANGE COLUMN `isActive` `is_active` BIT(1) NOT NULL DEFAULT b'1' ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
